<a href="https://colab.research.google.com/github/ShaliniSakthivel-DA/Python-Learning-CaseStudies/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Installing Numpy

!pip install numpy

# importing Numpy

import numpy as np


In [ ]:
# 1 Dimensional Array

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(f"\n 1D Array: {arr}")
type(arr)

# 2 Dimensional Array

arr2 = np.array([[1,2,3],[4,5,6]])

print(f"\n 2D Array: {arr2}")
type(arr2)


 1D Array: [ 1  2  3  4  5  6  7  8  9 10]

 2D Array: [[1 2 3]
 [4 5 6]]


numpy.ndarray

In [ ]:
#Range of values python:  range(), np.arange(start, stop, step)

arr = np.arange(0,5,2)
print(arr)

[0 2 4]


In [ ]:
#Evenly spaced values np.linespace(start,end,part of data)

arr = np.linspace(2,10,20)
print(arr)

[ 2.          2.42105263  2.84210526  3.26315789  3.68421053  4.10526316
  4.52631579  4.94736842  5.36842105  5.78947368  6.21052632  6.63157895
  7.05263158  7.47368421  7.89473684  8.31578947  8.73684211  9.15789474
  9.57894737 10.        ]


In [ ]:
# Create a 2D NumPy array with 2 rows and 3 columns
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [2, 4, 5]])
print(arr)
np.shape(arr)


[[1 2 3]
 [4 5 6]
 [2 4 5]]


9

In [ ]:
# Size()

np.size(arr)


9

In [ ]:
# data type

arr.dtype

dtype('int64')

In [ ]:
# number of dimensions -> 1D, 2D

arr.ndim

2

In [ ]:
# Create a 2D NumPy array with 2 rows and 3 columns
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.min())
print(np.argmax(arr))

1
5


In [ ]:
# Maximum value in the array
print(arr.max())
print(np.argmax(arr))

6
5


In [ ]:
# Sum of all elements
print(arr.sum())

21


In [ ]:
# Product of all elements
print(np.prod(arr))

720


In [ ]:
# Mean / Average of the array
print(arr.mean())
print(np.median(arr))
print(arr.var())
print(arr.std())

3.5
3.5
2.9166666666666665
1.707825127659933


In [ ]:
arr = np.array([[3.141, 2.718, 1.618],
                [4.669, 1.414, 2.236]])

arr.shape

(2, 3)

In [ ]:
# 1. np.reshape() → Change the shape of an array
arr.reshape(3,2)

array([[3.141, 2.718],
       [1.618, 4.669],
       [1.414, 2.236]])

In [ ]:
# 2. np.flatten() → Convert multi-dimensional ararr.
arr.flatten()

array([3.141, 2.718, 1.618, 4.669, 1.414, 2.236])

In [ ]:
# 3. np.sort() → Sort elements (row-wise by default)
np.sort(arr)

array([[1.618, 2.718, 3.141],
       [1.414, 2.236, 4.669]])

In [ ]:
# Sort **column-wise** (axis=1)
np.sort(arr,axis = 1)

array([[1.618, 2.718, 3.141],
       [1.414, 2.236, 4.669]])

In [ ]:
# 4. np.unique() → Find unique elements
np.unique(arr)

array([1.414, 1.618, 2.236, 2.718, 3.141, 4.669])

In [ ]:
# 5. np.round() → Round elements to specified decimals
np.round(arr,1)

array([[3.1, 2.7, 1.6],
       [4.7, 1.4, 2.2]])

In [ ]:
# 6. np.transpose(arr) → Transpose of array
np.transpose(arr)

array([[3.141, 4.669],
       [2.718, 1.414],
       [1.618, 2.236]])

In [ ]:
# 7. np.split(arr, sections) → Split array into equal sections
np.split(arr,2)

[array([[3.141, 2.718, 1.618]]), array([[4.669, 1.414, 2.236]])]

In [ ]:
arr1 = np.array([[3.141, 2.718, 1.618],
                [4.669, 1.414, 2.236]])

arr2 = np.array([[7.1, 8.2, 9.3],
                [10.4, 11.5, 12.6]])
# 8. np.concatenate() → Combine arrays

np.concatenate((arr1,arr2))

array([[ 3.141,  2.718,  1.618],
       [ 4.669,  1.414,  2.236],
       [ 7.1  ,  8.2  ,  9.3  ],
       [10.4  , 11.5  , 12.6  ]])

In [ ]:
# 9. np.hstack([arr1, arr2]) → Horizontal stack
np.hstack((arr1,arr2))

array([[ 3.141,  2.718,  1.618,  7.1  ,  8.2  ,  9.3  ],
       [ 4.669,  1.414,  2.236, 10.4  , 11.5  , 12.6  ]])

In [ ]:
# 10. np.vstack([arr1, arr2]) → Vertical stack
np.vstack((arr1,arr2))

array([[ 3.141,  2.718,  1.618],
       [ 4.669,  1.414,  2.236],
       [ 7.1  ,  8.2  ,  9.3  ],
       [10.4  , 11.5  , 12.6  ]])

In [ ]:
# 1. np.random.rand(d1, d2,..)
# Uniform random numbers in(0,1)
np.random.rand(5,10)


array([[0.36751996, 0.01717605, 0.65210932, 0.74845689, 0.77506825,
        0.06257338, 0.60092624, 0.16182373, 0.64952973, 0.47396213],
       [0.61394173, 0.45634977, 0.41353594, 0.34582387, 0.47168142,
        0.48758729, 0.69601873, 0.50425892, 0.76354027, 0.3830772 ],
       [0.75761774, 0.30980682, 0.52649646, 0.69996242, 0.28646915,
        0.46173856, 0.70078316, 0.78826327, 0.60484549, 0.35723194],
       [0.83439173, 0.91061519, 0.9401484 , 0.50831783, 0.04164117,
        0.64665267, 0.54727868, 0.957675  , 0.17857402, 0.02279048],
       [0.47996585, 0.76150062, 0.09913223, 0.0800276 , 0.75589921,
        0.47747459, 0.6254985 , 0.58592933, 0.54288846, 0.39888782]])

In [ ]:
# 2. np.random.randn(d1, d2, ...)
# Standard normal distribution (mean=0, std=1)
np.random.randn(5,10)

array([[-0.0190932 ,  1.01370871, -0.25329778,  1.01351367, -0.6261949 ,
         1.60489834, -0.82651826, -0.05061888,  0.62726894,  0.17610081],
       [-0.11993433,  0.694195  , -1.37139468,  0.84555787,  0.33483209,
         0.50347173, -1.56592124,  0.25050289, -2.04719373, -1.12675488],
       [ 0.75912534,  1.47800241, -1.60663337, -0.5501473 ,  1.79854198,
         0.09860731,  0.35446481,  1.51171078, -0.33023188,  0.06256453],
       [ 0.59246977, -0.52856086,  0.17127921, -0.33261661,  0.35332167,
        -0.75460591,  0.3811882 , -0.11076873, -0.31019834, -0.54826714],
       [-0.44072149,  0.37463692,  0.41463651, -2.39318502, -0.33122209,
         0.62720692, -0.49846839, -1.00576016,  0.01070561, -0.09612558]])

In [ ]:
# 3. np.random.randint(low, high, size)
#Random integers in a range

np.random.randint(10,200,10)

array([ 89, 175,  42, 147, 105, 114,  35, 184,  76, 164])

In [ ]:
#Matrix
np.random.randint(10,200,size= (5,2))

array([[162, 152],
       [155, 161],
       [159,  77],
       [ 24,  28],
       [ 63, 107]])

In [ ]:
# 4. np.random.choice(arr, size)
#Random sample from an existing array

arr = np.array([1,3,5,7,9])
np.random.choice(arr, size =100)

array([1, 7, 7, 1, 1, 9, 1, 3, 1, 7, 7, 5, 9, 1, 1, 3, 9, 3, 7, 7, 7, 1,
       1, 7, 7, 9, 1, 5, 5, 3, 5, 5, 7, 3, 3, 7, 3, 7, 3, 5, 5, 3, 9, 5,
       1, 3, 1, 7, 9, 9, 7, 9, 7, 1, 3, 3, 7, 1, 9, 7, 1, 7, 9, 5, 9, 5,
       9, 3, 5, 7, 1, 3, 3, 5, 1, 5, 9, 9, 1, 9, 1, 7, 9, 3, 1, 5, 3, 7,
       5, 7, 1, 5, 1, 5, 1, 5, 5, 3, 1, 7])

In [ ]:
# 5. np.random.seed(n)
#Set seed for reproducibility
np.random.seed(42)

In [ ]:
import numpy as np
import pandas as pd

# Set seed for reproducibility
np.random.seed(42)

# Generate data
data = {
    "Employee_ID": np.arange(1, 21),
    "Age": np.random.randint(20, 60, 20),
    "Salary": np.random.randint(25000, 100000, 20),
    "Department": np.random.choice(
        ["HR", "IT", "Finance", "Marketing"],
        20
    ),
    "Performance_Score": np.random.uniform(1, 5, 20).round(2),
    "Experience_Years": np.random.randint(0, 15, 20)
}

# Create DataFrame
df = pd.DataFrame(data)

In [ ]:
df

,Employee_ID,Age,Salary,Department,Performance_Score,Experience_Years
0,1,58,92969,HR,2.56,8
1,2,48,30311,Marketing,1.73,11
2,3,34,78707,IT,4.02,11
3,4,27,53693,IT,2.70,11
4,5,40,96932,IT,1.83,12
5,6,58,50658,HR,3.27,8
6,7,38,43431,IT,1.13,12
7,8,42,27747,HR,4.37,14
8,9,30,84150,IT,2.80,12
9,10,30,90725,Marketing,2.58,0


In [ ]:
# STUDENT PERFORMANCE ANALYSIS USING NUMPY

# Import NumPy library
import numpy as np

# Create Student Marks Dataset
# Rows -> Students
# Columns -> Subjects

marks = np.array([
    [78, 85, 90, 88, 76],   # Student A
    [65, 70, 60, 72, 68],   # Student B
    [90, 92, 88, 95, 91],   # Student C
    [45, 50, 55, 48, 52],   # Student D
    [80, 75, 85, 82, 79]    # Student E
])

# Store Student Names
students = np.array(["A", "B", "C", "D", "E"])

# Display Original Dataset
print("========== STUDENT MARKS ==========")
print(marks)

# Calculate Total Marks of Each Student
# axis = 1 -> Row-wise calculation

total_marks = np.sum(marks, axis=1)

print("\n========== TOTAL MARKS ==========")
print(total_marks)

# Calculate Average Marks of Each Student

average_marks = np.mean(marks, axis=1)

print("\n========== AVERAGE MARKS ==========")
print(average_marks)

# Find Highest Mark of Each Student

highest_marks = np.max(marks, axis=1)

print("\n========== HIGHEST MARKS ==========")
print(highest_marks)

# Find Lowest Mark of Each Student

lowest_marks = np.min(marks, axis=1)

print("\n========== LOWEST MARKS ==========")
print(lowest_marks)

# Calculate Percentage
# Total Marks = 500

percentage = (total_marks / 500) * 100

print("\n========== PERCENTAGE ==========")
print(percentage)

# Find Overall Average Total Marks

overall_average = np.mean(total_marks)

print("\n========== OVERALL AVERAGE ==========")
print(overall_average)

# Find Students Scoring Above Overall Average

above_average_students = students[total_marks > overall_average]

print("\n========== ABOVE AVERAGE STUDENTS ==========")
print(above_average_students)

# Find Failed Students
# If any subject mark is less than 50

failed_students = students[np.any(marks < 50, axis=1)]

print("\n========== FAILED STUDENTS ==========")
print(failed_students)

# Calculate Subject-wise Average
# axis = 0 -> Column-wise calculation

subject_average = np.mean(marks, axis=0)

print("\n========== SUBJECT-WISE AVERAGE ==========")
print(subject_average)

# Display Student-wise Report

print("\n========== STUDENT REPORT ==========")

for i in range(len(students)):

    print("\nStudent Name :", students[i])

    print("Marks :", marks[i])

    print("Total Marks :", total_marks[i])

    print("Average Marks :", average_marks[i])

    print("Highest Mark :", highest_marks[i])

    print("Lowest Mark :", lowest_marks[i])

    print("Percentage :", percentage[i])

# Rank Students Based on Total Marks
# argsort() sorts in ascending order
# [::-1] converts to descending order

ranking = np.argsort(total_marks)[::-1]

print("\n========== STUDENT RANKING ==========")

for rank, index in enumerate(ranking, start=1):

    print(f"Rank {rank} : Student {students[index]} "
          f"-> Total Marks = {total_marks[index]}")

========== STUDENT MARKS ==========
[[78 85 90 88 76]
 [65 70 60 72 68]
 [90 92 88 95 91]
 [45 50 55 48 52]
 [80 75 85 82 79]]

========== TOTAL MARKS ==========
[417 335 456 250 401]

========== AVERAGE MARKS ==========
[83.4 67.  91.2 50.  80.2]

========== HIGHEST MARKS ==========
[90 72 95 55 85]

========== LOWEST MARKS ==========
[76 60 88 45 75]

========== PERCENTAGE ==========
[83.4 67.  91.2 50.  80.2]

========== OVERALL AVERAGE ==========
371.8

========== ABOVE AVERAGE STUDENTS ==========
['A' 'C' 'E']

========== FAILED STUDENTS ==========
['D']

========== SUBJECT-WISE AVERAGE ==========
[71.6 74.4 75.6 77.  73.2]

========== STUDENT REPORT ==========

Student Name : A
Marks : [78 85 90 88 76]
Total Marks : 417
Average Marks : 83.4
Highest Mark : 90
Lowest Mark : 76
Percentage : 83.39999999999999

Student Name : B
Marks : [65 70 60 72 68]
Total Marks : 335
Average Marks : 67.0
Highest Mark : 72
Lowest Mark : 60
Percentage : 67.0

Student Name : C
Marks : [90 92 88 95 91]